### ISSUE TITLE
Create a single xlsx file for one / each method

### ISSUE THREAD

**Issue by ghost** [tcharts-boop/yahoo_finance_data_scrape#1]
Hi,
Thanks for the effort. Iam a newbee to python ( and coding). could you guide me on how to make the scraped data to be written in a single xlsx file for each method or even for a perticular method ( like income_statement)?
Best

**Comment by TedCha** [comment]
Hi @santosh1976,

Thanks for your comment! 

I would not advise using my application as I haven't had time to update it to reflect Yahoo Finance's current website structure. I would recommend using another Python Yahoo Finance Scraper such as [yfinance by ranaroussi](https://github.com/ranaroussi/yfinance). If you want to continue using my application for your use case, try editing the `write_xlsx_file` method in the `application_methods` class in `application.py` file to create your own custom method to write all of the returned dataframes into one single xlsx file.

When I have a little more time, I'll see if I can update this application to be a package and for it to allow different options for writing data (such as your own use case). Hopefully my comment can help you solve your use case in the meantime. 

Best,
Ted

**Comment by ghost** [comment]
Hi @tcharts-boop

Thanks for the reply. I did edit the said method in application.py and have successfully got the desired results.
Thanks again for the code.
best,
Santosh
