### ISSUE TITLE
How to change from yearly to quarterly results?

### ISSUE THREAD

**Issue by apavlo89** [tcharts-boop/yahoo_finance_data_scrape#2]
That would be super helpful! By the way, I love how easy it is to download data!

**Comment by TedCha** [comment]
@apavlo89 thanks for your kind words! 

Currently there is no way to change between annually/quarterly as I'm using a makeshift HTTP request to retrieve the data from Yahoo Finance. The change from annual to quarter data on the website is via an AJAX request which I can't simulate via an HTTP endpoint. If you wanted to play around with it, you could use Selenium WebDriver to request a browser version of the website and then change to the quarterly data. 

Currently I'm in the midst of graduating so I won't have time to update it for a while. As soon as I get the chance, I'll refactor it to be more flexible for different use cases.
